<a href="https://colab.research.google.com/github/Ryuta-Y/pytorch-practice/blob/main/pytorch_practice_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%matplotlib inline

In [2]:
import torch
import numpy as np

In [3]:
data=[[1,2],[3,4]]
x_data=torch.tensor(data)
#print(data)
#print(x_data)

In [4]:
np_array=np.array(data)
x_np=torch.from_numpy(np_array)
#print(np_array)
#print(x_np)

In [5]:
x_ones=torch.ones_like(x_data)
print(x_ones)
x_rand=torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.7730, 0.4441],
        [0.3846, 0.3481]])


In [6]:
tensor=torch.rand(3,4,)
zeros_tensor=torch.zeros(tensor.shape, dtype=torch.float)
print(tensor)
print(zeros_tensor)
print(tensor.device)
print(zeros_tensor.device)



tensor([[0.3894, 0.5937, 0.0898, 0.6306],
        [0.8536, 0.2244, 0.9405, 0.4238],
        [0.8971, 0.2983, 0.0399, 0.9676]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
cpu
cpu


In [7]:
if torch.cuda.is_available():
  tensor=tensor.to('cuda')
print(tensor.device)

cuda:0


In [8]:
tensor=torch.rand(4,4)
print(tensor)
print(tensor[0,:])
print(tensor[1])
print(tensor[:,0])
print(tensor[...,-1])
tensor[:,1]=0
print(tensor)


tensor([[0.1889, 0.9097, 0.6829, 0.1118],
        [0.5405, 0.3498, 0.6053, 0.7788],
        [0.1852, 0.8503, 0.9092, 0.8866],
        [0.7128, 0.0750, 0.1215, 0.4514]])
tensor([0.1889, 0.9097, 0.6829, 0.1118])
tensor([0.5405, 0.3498, 0.6053, 0.7788])
tensor([0.1889, 0.5405, 0.1852, 0.7128])
tensor([0.1118, 0.7788, 0.8866, 0.4514])
tensor([[0.1889, 0.0000, 0.6829, 0.1118],
        [0.5405, 0.0000, 0.6053, 0.7788],
        [0.1852, 0.0000, 0.9092, 0.8866],
        [0.7128, 0.0000, 0.1215, 0.4514]])


In [9]:
t1=torch.cat([tensor,tensor,tensor],dim=1)
print(t1)
print(t1.shape)
t2=torch.cat([tensor,tensor,tensor],dim=0)
print(t2)
print(t2.shape)

tensor([[0.1889, 0.0000, 0.6829, 0.1118, 0.1889, 0.0000, 0.6829, 0.1118, 0.1889,
         0.0000, 0.6829, 0.1118],
        [0.5405, 0.0000, 0.6053, 0.7788, 0.5405, 0.0000, 0.6053, 0.7788, 0.5405,
         0.0000, 0.6053, 0.7788],
        [0.1852, 0.0000, 0.9092, 0.8866, 0.1852, 0.0000, 0.9092, 0.8866, 0.1852,
         0.0000, 0.9092, 0.8866],
        [0.7128, 0.0000, 0.1215, 0.4514, 0.7128, 0.0000, 0.1215, 0.4514, 0.7128,
         0.0000, 0.1215, 0.4514]])
torch.Size([4, 12])
tensor([[0.1889, 0.0000, 0.6829, 0.1118],
        [0.5405, 0.0000, 0.6053, 0.7788],
        [0.1852, 0.0000, 0.9092, 0.8866],
        [0.7128, 0.0000, 0.1215, 0.4514],
        [0.1889, 0.0000, 0.6829, 0.1118],
        [0.5405, 0.0000, 0.6053, 0.7788],
        [0.1852, 0.0000, 0.9092, 0.8866],
        [0.7128, 0.0000, 0.1215, 0.4514],
        [0.1889, 0.0000, 0.6829, 0.1118],
        [0.5405, 0.0000, 0.6053, 0.7788],
        [0.1852, 0.0000, 0.9092, 0.8866],
        [0.7128, 0.0000, 0.1215, 0.4514]])
torch.Size([12

In [10]:
print(tensor)
print(tensor.T)

tensor@tensor.T

tensor([[0.1889, 0.0000, 0.6829, 0.1118],
        [0.5405, 0.0000, 0.6053, 0.7788],
        [0.1852, 0.0000, 0.9092, 0.8866],
        [0.7128, 0.0000, 0.1215, 0.4514]])
tensor([[0.1889, 0.5405, 0.1852, 0.7128],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.6829, 0.6053, 0.9092, 0.1215],
        [0.1118, 0.7788, 0.8866, 0.4514]])


tensor([[0.5145, 0.6025, 0.7550, 0.2681],
        [0.6025, 1.2650, 1.3409, 0.8104],
        [0.7550, 1.3409, 1.6470, 0.6427],
        [0.2681, 0.8104, 0.6427, 0.7266]])

In [11]:
agg = tensor.sum()
agg_item=agg.item()
print(agg)
print(agg_item)
print(type(agg))
print(type(agg_item))

tensor(6.1749)
6.174900054931641
<class 'torch.Tensor'>
<class 'float'>


In [12]:
print(tensor)
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[0.1889, 0.0000, 0.6829, 0.1118],
        [0.5405, 0.0000, 0.6053, 0.7788],
        [0.1852, 0.0000, 0.9092, 0.8866],
        [0.7128, 0.0000, 0.1215, 0.4514]])
tensor([[0.1889, 0.0000, 0.6829, 0.1118],
        [0.5405, 0.0000, 0.6053, 0.7788],
        [0.1852, 0.0000, 0.9092, 0.8866],
        [0.7128, 0.0000, 0.1215, 0.4514]]) 

tensor([[5.1889, 5.0000, 5.6829, 5.1118],
        [5.5405, 5.0000, 5.6053, 5.7788],
        [5.1852, 5.0000, 5.9092, 5.8866],
        [5.7128, 5.0000, 5.1215, 5.4514]])


In [13]:
t=torch.ones(5)
print(t)
n=t.numpy()
print(n)

t.add_(1)

print(t)
print(n)


tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [17]:
n=np.ones(5)
t=torch.from_numpy(n)

print(n)
print(t)

np.add(n,1,out=n)


[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


array([2., 2., 2., 2., 2.])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')